### ISSUE TITLE
remove `group:` prefix from snippets

### ISSUE THREAD

**Issue by saerdnaer** [Intility/vscode-backstage#2]
it looks like the official schemas recommend to only use the `user:` prefix, but not the `group:` prefix. Maybe the snippets should conform to the schema?

**Comment by emilkje** [comment]
Thanks for your feedback. Do you mean prefix for entity references? I can't find anything in the docs outlining this recommendation. In fact the [Entity Reference](https://backstage.io/docs/features/software-catalog/references#string-references) documentation is using the `group` prefix in the example.
